SELECT ''''||'02'||''','''||'Elca Cosmeticos'||''','''||H.TNOM_TIPNOM||''','''||C.DESNOM||''','''||TRIM(H.FICTRA)||''','''||TRIM(H.CEDULA)
||''','''||TO_CHAR(H.FECING, 'DD/MM/YYYY')||''','''||H.APELL1||''','''||H.APELL2||''','''||H.NOMBR1||''','''||H.NOMBR2
||''','''||H.CGO_CAROCU||''','''||D.DESCAR||''','''||H.LOCA_CODLOC||''','''||E.DESLO1||''','''||H.SCS_CODSUC||''','''||F.DESSUC
||''','''||'01'||''','''||'UNICA'||''','''||H.DPTO_CODDEP||''','''||G.DESDEP||''','''||H.SUELD1*30||''','''||I.FUNCTO||''','''||A.CTO_CODCTO||''','''||I.DESCTO
||''','''||A.CANCTO||''','''||A.MONCTO||''','''||A.SALDOT||''','''||J.TOASIG||''','''||J.TODEDU||''','''||J.TONETO||''','''||A.FPRO_ANOCAL||''','''||trim(A.MESCAL)
||''','''||A.FPRO_NUMPER||''','''||K.DESPER||''','''||DECODE(H.FECRET,NULL,'0','1')||''','''||secautosrv.nextval||'''' 
FROM NMM001 H, NMT001 B, NMT003 C, NMT004 D, NMT002 E, NMT038 F, NMT019 G, NMM024 A, NMT027 I, NMM023 J, NMT033 K
WHERE H.CIA_CODCIA=B.CODCIA
AND H.CIA_CODCIA=C.CIA_CODCIA
AND H.TNOM_TIPNOM=C.TIPNOM
AND H.CIA_CODCIA=D.CIA_CODCIA
AND H.CGO_CAROCU=D.CODCAR
AND H.CIA_CODCIA=E.CIA_CODCIA
AND H.LOCA_CODLOC=E.CODLOC
AND H.CIA_CODCIA=F.CIA_CODCIA
AND H.SCS_CODSUC=F.CODSUC
AND H.CIA_CODCIA=G.CIA_CODCIA
AND H.DPTO_CODDEP=G.CODDEP
AND H.CIA_CODCIA=H.CIA_CODCIA
AND H.FICTRA=A.TRAB_FICTRA
AND A.CIA_CODCIA=I.CIA_CODCIA
AND A.TNOM_TIPNOM=I.TNOM_TIPNOM
AND A.CTO_CODCTO=I.CODCTO
AND I.FUNCTO IN ('1','2')
AND I.NOIMPR='0'
AND A.CIA_CODCIA=J.CIA_CODCIA
AND A.TNOM_TIPNOM=J.TNOM_TIPNOM
AND A.TRAB_FICTRA=J.TRAB_FICTRA
AND A.PROC_TIPPRO=J.PROC_TIPPRO
AND A.SUBPRO=J.SUBPRO
AND A.FPRO_ANOCAL=J.FPRO_ANOCAL
AND A.FPRO_NUMPER=J.FPRO_NUMPER
AND A.CIA_CODCIA=K.CIA_CODCIA
AND A.TNOM_TIPNOM=K.TNOM_TIPNOM
AND A.PROC_TIPPRO=K.PROC_TIPPRO
AND A.SUBPRO=K.SUBPRO
AND A.FPRO_ANOCAL=K.ANOCAL
AND A.FPRO_NUMPER=K.NUMPER
AND A.PROC_TIPPRO IN ('1','4','2','3','8')
--and trim(a.trab_fictra)='0287'
--and a.fpro_anocal like '1998' and trim(a.mescal) like '7' and a.fpro_numper=13